# 日志收集配置文件示例
# 请根据实际环境修改相关配置

# 日志记录配置
logging:
  level: INFO
  file: collector.log

# 是否压缩日志文件
compress_logs: true

# 服务器配置列表
servers:
  # SSH 服务器配置
  - protocol: ssh
    host: 192.168.1.100
    port: 22
    username: deploy
    # password: your_password  # 可选，建议使用密钥认证
    key_file: ~/.ssh/id_rsa    # SSH 私钥文件路径
    local_path: ./logs/server1
    log_paths:
      - /var/log/apache2
      - /var/log/nginx
      - /var/log/application

  # HTTP 服务器配置
  - protocol: http
    local_path: ./logs/http_logs
    log_urls:
      - http://example.com/logs/access.log
      - http://example.com/logs/error.log

  # FTP 服务器配置
  - protocol: ftp
    host: ftp.example.com
    port: 21
    username: ftpuser
    password: ftppass
    local_path: ./logs/ftp_logs
    log_paths:
      - /logs/web
      - /logs/app